# Generated by Django 5.2.7 on 2025-10-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StringAnalysis",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("value", models.TextField(unique=True)),
                ("properties", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "string_analyses",
                "ordering": ["-created_at"],
            },
        ),
    ]
